#!/usr/bin/env bash
# Build /workspace/.env from process environment (Cursor Cloud Secrets).
# Does not print secret values. Safe to run on every agent session after secrets exist.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
EXAMPLE="$ROOT/.env.example"

if [[ ! -f "$EXAMPLE" ]]; then
  echo "ERROR: missing .env.example" >&2
  exit 1
fi

# Keys we copy from environment when set (matches .env.example + common aliases)
KEYS=(
  SUPABASE_URL SUPABASE_KEY SUPABASE_ANON_KEY SUPABASE_USE_LEGACY_ANON_KEY SUPABASE_HTTP_TIMEOUT_SEC
  TELEGRAM_TOKEN TELEGRAM_BOT_TOKEN TG_BOT_TOKEN
  TELEGRAM_GROUP_CHAT_ID TELEGRAM_GROUP_ID TG_GROUP_ID TELEGRAM_CHAT_ID
  TELEGRAM_WEBHOOK_SECRET WEBHOOK_BASE_URL WEBHOOK_FULL_URL RAILWAY_PUBLIC_DOMAIN
  TG_API_ID TG_API_HASH PORT LOG_LEVEL
  TICKETS_TABLE SALES_CASES_TABLE ATTENDANCE_LOGS_TABLE TICKET_PHOTOS_BUCKET
  TELEGRAM_ALLOWED_USERNAMES BOT_SESSIONS_TABLE
  DASHBOARD_ADMIN_USERNAMES DASHBOARD_PASSWORD DASHBOARD_OPERATOR_ALLOWLIST DASHBOARD_SESSION_SECRET
  CRON_SECRET UNATTENDED_NUDGE_HOURS UNATTENDED_POLL_MINUTES
  FIELD_ENGINEERS_TABLE TASK_CATEGORIES_TABLE FIELD_RESPONSE_UNDO_MINUTES
  TELEGRAM_GROUP_TELETHON_INGEST TELEGRAM_DELETE_WEBHOOK_ON_SHUTDOWN
  HTTPS_PROXY HTTP_PROXY
)

copy_key() {
  local k="$1"
  local v="${!k-}"
  if [[ -n "${v// }" ]]; then
    printf '%s=%s\n' "$k" "$v"
  fi
}

{
  echo "# Generated by scripts/write_dotenv_from_environment.sh — do not commit."
  echo "# Source: Cursor Secrets / process environment."
  echo ""
  for k in "${KEYS[@]}"; do
    copy_key "$k" || true
  done
} >"$ENV_FILE"

# Require minimum for bot import
missing=()
[[ -z "${SUPABASE_URL:-}" ]] && missing+=("SUPABASE_URL")
[[ -z "${SUPABASE_KEY:-}${SUPABASE_ANON_KEY:-}" ]] && missing+=("SUPABASE_KEY or SUPABASE_ANON_KEY")
[[ -z "${TELEGRAM_TOKEN:-}${TELEGRAM_BOT_TOKEN:-}${TG_BOT_TOKEN:-}" ]] && missing+=("TELEGRAM_TOKEN")

if ((${#missing[@]})); then
  echo "Wrote $ENV_FILE but still missing: ${missing[*]}" >&2
  echo "Add those as Cursor Secrets, then re-run this script." >&2
  exit 2
fi

chmod 600 "$ENV_FILE" 2>/dev/null || true
echo "OK — wrote $ENV_FILE ($(wc -l <"$ENV_FILE") lines from environment)."
