-- Historical attendance + multi-day tracking migration.
--
-- Three changes, run in order:
--   1. Rename `public.tickets` to `public.tickets_active` (clearer semantics
--      now that we have a history table alongside it).
--   2. Add `last_assigned_at` to `tickets_active` so the dashboard can offer
--      a "Days to Look Back" filter even if the row was first created long ago.
--   3. Create `ticket_attendance_logs` — append-only history of every
--      assignment + every field response, FK-linked to `tickets_active`.
--
-- All steps are idempotent (safe to re-run). RLS policies for the `anon`
-- role mirror the existing policies on tickets: SELECT + INSERT are open,
-- UPDATE/DELETE are intentionally NOT granted on the logs table (history is
-- append-only by design).

-- --------------------------------------------------------------------
-- 1) Rename `tickets` -> `tickets_active` (idempotent)
-- --------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'tickets'
  ) and not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'tickets_active'
  ) then
    alter table public.tickets rename to tickets_active;
  end if;
end$$;

-- --------------------------------------------------------------------
-- 2) `last_assigned_at` (used by the dashboard's date filter)
-- --------------------------------------------------------------------
alter table public.tickets_active
  add column if not exists last_assigned_at timestamptz default now();

-- Backfill existing rows once so the new column is never NULL.
update public.tickets_active
  set last_assigned_at = coalesce(updated_at, created_at, now())
  where last_assigned_at is null;

-- --------------------------------------------------------------------
-- 3) Attendance history table
-- --------------------------------------------------------------------
create table if not exists public.ticket_attendance_logs (
  id              bigint generated by default as identity primary key,
  ticket_number   text references public.tickets_active(ticket_number),
  member_username text not null,
  action_type     text not null check (action_type in ('Assignment', 'Response')),
  note            text,
  photo_url       text,
  "timestamp"     timestamptz not null default now()
);

create index if not exists idx_attendance_logs_ticket
  on public.ticket_attendance_logs (ticket_number);
create index if not exists idx_attendance_logs_member_lower
  on public.ticket_attendance_logs (lower(member_username));
create index if not exists idx_attendance_logs_ts
  on public.ticket_attendance_logs ("timestamp" desc);

-- --------------------------------------------------------------------
-- 4) RLS policies for the `anon` role
-- --------------------------------------------------------------------
alter table public.ticket_attendance_logs enable row level security;

drop policy if exists "attendance_logs_anon_select" on public.ticket_attendance_logs;
drop policy if exists "attendance_logs_anon_insert" on public.ticket_attendance_logs;

create policy "attendance_logs_anon_select"
  on public.ticket_attendance_logs
  for select
  to anon
  using (true);

create policy "attendance_logs_anon_insert"
  on public.ticket_attendance_logs
  for insert
  to anon
  with check (true);
-- Intentionally no UPDATE / DELETE policy — history is append-only.
