[theme]
primaryColor = "#D7B491"
backgroundColor = "#0B0B0B"
secondaryBackgroundColor = "#0B0B0B"
textColor = "#e8e6e3"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
